package migrate

import (
	"strings"
	"testing"
)

func TestConvertToTOMLBasic(t *testing.T) {
	ir := &MakefileIR{
		Variables: []MakeVar{
			{Name: "CC", Value: "gcc", Flavor: "="},
			{Name: "CFLAGS", Value: "-Wall -g", Flavor: ":="},
		},
		Targets: []MakeTarget{
			{
				Name:    "build",
				Comment: "Compile the project",
				Recipe:  []string{"$(CC) $(CFLAGS) -o app main.c"},
				IsPhony: true,
			},
		},
		DefaultGoal: "build",
	}

	toml := ConvertToTOML(ir)

	// Check header
	if !strings.Contains(toml, "# Generated by imlazy migrate from Makefile") {
		t.Error("missing header")
	}

	// Check settings
	if !strings.Contains(toml, `default = "build"`) {
		t.Error("missing default setting")
	}

	// Check variables
	if !strings.Contains(toml, `cc = "gcc"`) {
		t.Error("missing cc variable")
	}
	if !strings.Contains(toml, `cflags = "-Wall -g"`) {
		t.Error("missing cflags variable")
	}

	// Check command
	if !strings.Contains(toml, "[commands.build]") {
		t.Error("missing build command")
	}
	if !strings.Contains(toml, `desc = "Compile the project"`) {
		t.Error("missing description")
	}
	if !strings.Contains(toml, "{{cc}}") {
		t.Error("variable reference not converted")
	}
}

func TestConvertToTOMLWithEnv(t *testing.T) {
	ir := &MakefileIR{
		Variables: []MakeVar{
			{Name: "API_KEY", Value: "secret", Flavor: "=", Export: true},
			{Name: "CC", Value: "gcc", Flavor: "=", Export: false},
		},
		Targets: []MakeTarget{
			{Name: "build", Recipe: []string{"echo hi"}, IsPhony: true},
		},
		DefaultGoal: "build",
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, "[env]") {
		t.Error("missing [env] section")
	}
	if !strings.Contains(toml, `API_KEY = "secret"`) {
		t.Error("missing exported variable in env section")
	}
	if !strings.Contains(toml, "[variables]") {
		t.Error("missing [variables] section")
	}
	if !strings.Contains(toml, `cc = "gcc"`) {
		t.Error("missing non-exported variable in variables section")
	}
}

func TestConvertToTOMLDepsFiltering(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{
				Name:          "all",
				Prerequisites: []string{"build", "test", "main.o"},
				IsPhony:       true,
			},
			{
				Name:    "build",
				Recipe:  []string{"go build"},
				IsPhony: true,
			},
			{
				Name:    "test",
				Recipe:  []string{"go test"},
				IsPhony: true,
			},
		},
		DefaultGoal: "all",
	}

	toml := ConvertToTOML(ir)

	// "all" should have dep = ["build", "test"] but NOT "main.o"
	if !strings.Contains(toml, `dep = ["build", "test"]`) {
		t.Errorf("dep list should only include actual targets, got:\n%s", toml)
	}
}

func TestConvertToTOMLTargetFiltering(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{Name: "build", Recipe: []string{"go build"}, IsPhony: true},
			{Name: "%.o", IsPattern: true, Recipe: []string{"gcc -c $<"}},
			{Name: ".SUFFIXES", IsDotTarget: true},
			{Name: "main.o", Recipe: []string{"gcc -c main.c"}},
		},
		DefaultGoal: "build",
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, "[commands.build]") {
		t.Error("build should be included")
	}
	if strings.Contains(toml, "%.o") {
		t.Error("pattern rules should be filtered out")
	}
	if strings.Contains(toml, "SUFFIXES") {
		t.Error("dot targets should be filtered out")
	}
	if strings.Contains(toml, "main.o") {
		t.Error("file targets should be filtered out")
	}
}

func TestConvertToTOMLBuiltinRename(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{Name: "help", Recipe: []string{"echo help"}, IsPhony: true},
			{Name: "version", Recipe: []string{"echo v1"}, IsPhony: true},
		},
		DefaultGoal: "help",
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, "[commands.make_help]") {
		t.Error("'help' should be renamed to 'make_help'")
	}
	if !strings.Contains(toml, "[commands.make_version]") {
		t.Error("'version' should be renamed to 'make_version'")
	}
	if !strings.Contains(toml, `default = "make_help"`) {
		t.Error("default goal should reference renamed target")
	}
}

func TestConvertToTOMLMultiLineRecipe(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{
				Name: "deploy",
				Recipe: []string{
					"echo 'Building...'",
					"go build -o app",
					"scp app server:/opt/",
				},
				IsPhony: true,
			},
		},
		DefaultGoal: "deploy",
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, "run = [\n") {
		t.Error("multi-line recipe should use multi-line array format")
	}
}

func TestConvertToTOMLSingleLineRecipe(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{
				Name:    "test",
				Recipe:  []string{"go test ./..."},
				IsPhony: true,
			},
		},
		DefaultGoal: "test",
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, `run = ["go test ./..."]`) {
		t.Errorf("single-line recipe should be inline, got:\n%s", toml)
	}
}

func TestConvertToTOMLWarnings(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{Name: "build", Recipe: []string{"echo hi"}, IsPhony: true},
		},
		DefaultGoal: "build",
		Warnings:    []string{"something could not be converted"},
	}

	toml := ConvertToTOML(ir)

	if !strings.Contains(toml, "# Migration warnings:") {
		t.Error("warnings section missing")
	}
	if !strings.Contains(toml, "# - something could not be converted") {
		t.Error("warning text missing")
	}
}

func TestConvertToTOMLNoVarsSection(t *testing.T) {
	ir := &MakefileIR{
		Targets: []MakeTarget{
			{Name: "build", Recipe: []string{"go build"}, IsPhony: true},
		},
		DefaultGoal: "build",
	}

	toml := ConvertToTOML(ir)

	if strings.Contains(toml, "[variables]") {
		t.Error("[variables] section should be omitted when empty")
	}
	if strings.Contains(toml, "[env]") {
		t.Error("[env] section should be omitted when empty")
	}
}

func TestFormatRunArray(t *testing.T) {
	single := formatRunArray([]string{"go build"})
	if single != `run = ["go build"]`+"\n" {
		t.Errorf("single: got %q", single)
	}

	multi := formatRunArray([]string{"mkdir -p bin", "go build -o bin/app"})
	if !strings.Contains(multi, "run = [\n") {
		t.Error("multi should use multi-line format")
	}
}

func TestFormatStringArray(t *testing.T) {
	single := formatStringArray("dep", []string{"build"})
	if single != `dep = ["build"]`+"\n" {
		t.Errorf("single: got %q", single)
	}

	multi := formatStringArray("dep", []string{"build", "lint"})
	if multi != `dep = ["build", "lint"]`+"\n" {
		t.Errorf("multi: got %q", multi)
	}
}

func TestFilterVars(t *testing.T) {
	vars := []MakeVar{
		{Name: "CC", Export: false},
		{Name: "API_KEY", Export: true},
		{Name: "CFLAGS", Export: false},
	}

	nonExported := filterVars(vars, false)
	if len(nonExported) != 2 {
		t.Errorf("expected 2 non-exported, got %d", len(nonExported))
	}

	exported := filterVars(vars, true)
	if len(exported) != 1 {
		t.Errorf("expected 1 exported, got %d", len(exported))
	}
}

func TestFilterDeps(t *testing.T) {
	targetNames := map[string]bool{"build": true, "test": true}
	prereqs := []string{"build", "test", "main.o", "utils.o"}

	deps := filterDeps(prereqs, targetNames)
	if len(deps) != 2 {
		t.Fatalf("expected 2 deps, got %d", len(deps))
	}
	if deps[0] != "build" || deps[1] != "test" {
		t.Errorf("got %v", deps)
	}
}
