package migrate

import (
	"fmt"
	"path/filepath"
	"strings"
)

// ConvertToTOML generates a lazy.toml string from a MakefileIR.
func ConvertToTOML(ir *MakefileIR) string {
	var b strings.Builder

	source := ir.Source
	if source == "" {
		source = "Makefile"
	}
	b.WriteString(fmt.Sprintf("# Generated by imlazy migrate from %s\n\n", source))
	if ir.SourcePath != "" {
		b.WriteString(fmt.Sprintf("# imlazy-source: %s\n", filepath.ToSlash(ir.SourcePath)))
		if ir.SourceHash != "" {
			b.WriteString(fmt.Sprintf("# imlazy-source-hash: %s\n", ir.SourceHash))
		}
		b.WriteString("\n")
	}

	// [settings]
	writeSettings(&b, ir)

	// [variables]
	writeVariables(&b, ir)

	// [env]
	writeEnv(&b, ir)

	// [commands]
	writeCommands(&b, ir)

	// Warnings as comments at the end
	writeWarnings(&b, ir)

	return b.String()
}

// writeSettings writes the [settings] section to the TOML output.
func writeSettings(b *strings.Builder, ir *MakefileIR) {
	b.WriteString("[settings]\n")
	if ir.DefaultGoal != "" {
		sanitized := SanitizeTargetName(ir.DefaultGoal)
		b.WriteString(fmt.Sprintf("default = %q\n", sanitized))
	}
	if ir.SourcePath != "" {
		b.WriteString("include = [\".lazy.local.toml\"]\n")
	}
	b.WriteString("\n")
}

// writeVariables writes the [variables] section with non-exported Make variables.
func writeVariables(b *strings.Builder, ir *MakefileIR) {
	vars := filterVars(ir.Variables, false)
	if len(vars) == 0 {
		return
	}

	b.WriteString("[variables]\n")
	for _, v := range vars {
		name := strings.ToLower(v.Name)
		value := ConvertVarRefs(v.Value, ir, nil)
		b.WriteString(fmt.Sprintf("%s = %q\n", name, value))
	}
	b.WriteString("\n")
}

// writeEnv writes the [env] section with exported Make variables.
func writeEnv(b *strings.Builder, ir *MakefileIR) {
	vars := filterVars(ir.Variables, true)
	if len(vars) == 0 {
		return
	}

	b.WriteString("[env]\n")
	for _, v := range vars {
		value := ConvertVarRefs(v.Value, ir, nil)
		b.WriteString(fmt.Sprintf("%s = %q\n", v.Name, value))
	}
	b.WriteString("\n")
}

// writeCommands writes the [commands] section, converting Make targets to ImLazy commands.
func writeCommands(b *strings.Builder, ir *MakefileIR) {
	targets := mergeTargets(ir.Targets)
	// Build set of target names for dependency resolution
	targetNames := make(map[string]bool)
	for _, t := range targets {
		if !ShouldSkipTarget(t) {
			targetNames[t.Name] = true
		}
	}

	b.WriteString("[commands]\n\n")

	for _, t := range targets {
		if ShouldSkipTarget(t) {
			continue
		}

		name := SanitizeTargetName(t.Name)
		if strings.Contains(name, ":") {
			// Namespaced names (npm-style "test:watch") need quoted keys.
			b.WriteString(fmt.Sprintf("[commands.%q]\n", name))
		} else {
			b.WriteString(fmt.Sprintf("[commands.%s]\n", name))
		}

		// Description from comment
		if t.Comment != "" {
			b.WriteString(fmt.Sprintf("desc = %q\n", t.Comment))
		}

		// Recipe → run array
		if len(t.Recipe) > 0 {
			convertedRecipe := make([]string, 0, len(t.Recipe))
			for _, line := range t.Recipe {
				converted := ConvertVarRefs(line, ir, &t)
				converted = cleanRecipeLine(converted)
				convertedRecipe = append(convertedRecipe, converted)
			}
			b.WriteString(formatRunArray(convertedRecipe))
		}

		// Dependencies — only include prerequisites that are also targets
		deps := filterDeps(t.Prerequisites, targetNames)
		if len(deps) > 0 {
			sanitizedDeps := make([]string, len(deps))
			for i, d := range deps {
				sanitizedDeps[i] = SanitizeTargetName(d)
			}
			b.WriteString(formatStringArray("dep", sanitizedDeps))
		}

		b.WriteString("\n")
	}
}

// mergeTargets combines repeated rules for the same target. Makefiles often
// declare prerequisites separately from recipes; emitting duplicate TOML
// tables for those rules would make the migrated config invalid.
func mergeTargets(targets []MakeTarget) []MakeTarget {
	indexes := make(map[string]int)
	result := make([]MakeTarget, 0, len(targets))
	for _, target := range targets {
		if index, ok := indexes[target.Name]; ok {
			existing := &result[index]
			existing.Prerequisites = appendUnique(existing.Prerequisites, target.Prerequisites...)
			existing.Recipe = append(existing.Recipe, target.Recipe...)
			existing.IsPhony = existing.IsPhony || target.IsPhony
			if existing.Comment == "" {
				existing.Comment = target.Comment
			}
			continue
		}
		indexes[target.Name] = len(result)
		result = append(result, target)
	}
	return result
}

func appendUnique(values []string, additions ...string) []string {
	seen := make(map[string]bool, len(values)+len(additions))
	for _, value := range values {
		seen[value] = true
	}
	for _, value := range additions {
		if !seen[value] {
			values = append(values, value)
			seen[value] = true
		}
	}
	return values
}

// writeWarnings appends migration warnings as TOML comments at the end of the output.
func writeWarnings(b *strings.Builder, ir *MakefileIR) {
	if len(ir.Warnings) == 0 {
		return
	}
	b.WriteString("# Migration warnings:\n")
	for _, w := range ir.Warnings {
		b.WriteString(fmt.Sprintf("# - %s\n", w))
	}
}

// filterVars returns variables matching the export flag.
func filterVars(vars []MakeVar, exported bool) []MakeVar {
	var result []MakeVar
	for _, v := range vars {
		if v.Export == exported {
			result = append(result, v)
		}
	}
	return result
}

// filterDeps returns only prerequisites that are actual target names.
func filterDeps(prereqs []string, targetNames map[string]bool) []string {
	var deps []string
	for _, p := range prereqs {
		if targetNames[p] {
			deps = append(deps, p)
		}
	}
	return deps
}

// cleanRecipeLine removes leftover Make-isms from a converted recipe line.
// Strips {{q}} (Make's $(Q) quiet variable) and trims whitespace.
func cleanRecipeLine(line string) string {
	// $(Q) was already stripped in the parser, but if it appeared as a
	// variable reference it became {{q}} — strip that too
	line = strings.TrimPrefix(line, "{{q}}")
	line = strings.TrimSpace(line)
	return line
}

// formatRunArray formats a slice of strings as a TOML run array.
func formatRunArray(lines []string) string {
	if len(lines) == 1 {
		return fmt.Sprintf("run = [%q]\n", lines[0])
	}
	var b strings.Builder
	b.WriteString("run = [\n")
	for _, line := range lines {
		b.WriteString(fmt.Sprintf("  %q,\n", line))
	}
	b.WriteString("]\n")
	return b.String()
}

// formatStringArray formats a named TOML string array.
func formatStringArray(key string, items []string) string {
	if len(items) == 1 {
		return fmt.Sprintf("%s = [%q]\n", key, items[0])
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s = [", key))
	for i, item := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", item))
	}
	b.WriteString("]\n")
	return b.String()
}
