package migrate

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// ConvertToTOML generates a lazy.toml string from a MakefileIR.
func ConvertToTOML(ir *MakefileIR) string {
	var b strings.Builder

	source := ir.Source
	if source == "" {
		source = "Makefile"
	}
	b.WriteString(fmt.Sprintf("# Generated by imlazy migrate from %s\n\n", source))

	// Commands and variables are rendered first so their {{placeholders}} can
	// be scanned before the [variables] table is written.
	var vars, env, commands strings.Builder
	writeVariables(&vars, ir)
	writeEnv(&env, ir)
	writeCommands(&commands, ir)

	// [settings]
	writeSettings(&b, ir)

	// [variables] (plus defaults for variables the Makefile never assigned)
	b.WriteString(withUndeclaredVars(vars.String(), ir,
		vars.String()+env.String()+commands.String()))

	// [env]
	b.WriteString(env.String())

	// [commands]
	b.WriteString(commands.String())

	// Warnings as comments at the end
	writeWarnings(&b, ir)

	return b.String()
}

// placeholderRe matches an ImLazy {{var}} placeholder in generated output.
var placeholderRe = regexp.MustCompile(`\{\{(\w+)\}\}`)

// builtinPlaceholders are resolved by ImLazy itself, not by [variables].
var builtinPlaceholders = map[string]bool{"os": true, "arch": true, "cwd": true, "args": true}

// withUndeclaredVars appends defaults for variables the generated config
// references but never defines. A Makefile leaves DESTDIR and friends unset
// and make expands them to nothing; without a default ImLazy would prompt for
// them, or leave "{{destdir}}" in the command when nothing can prompt.
func withUndeclaredVars(varsSection string, ir *MakefileIR, generated string) string {
	// Only Makefiles get this. A justfile's {{param}} placeholders are recipe
	// parameters, and prompting for those beats silently running them empty.
	if ir.Source != "" && ir.Source != "Makefile" {
		return varsSection
	}

	declared := make(map[string]bool)
	exported := make(map[string]MakeVar)
	for _, v := range ir.Variables {
		if v.Export {
			exported[SanitizeVarName(v.Name)] = v
			continue
		}
		declared[SanitizeVarName(v.Name)] = true
	}

	var missing []string
	seen := make(map[string]bool)
	for _, m := range placeholderRe.FindAllStringSubmatch(generated, -1) {
		name := m[1]
		if declared[name] || builtinPlaceholders[name] || seen[name] {
			continue
		}
		seen[name] = true
		missing = append(missing, name)
	}
	if len(missing) == 0 {
		return varsSection
	}
	sort.Strings(missing)

	var b strings.Builder
	if varsSection == "" {
		b.WriteString("[variables]\n")
	} else {
		b.WriteString(strings.TrimRight(varsSection, "\n"))
		b.WriteString("\n")
	}
	b.WriteString("\n# Referenced but never assigned in the source; empty by default,\n")
	b.WriteString("# as in make. Override at run time: imlazy <command> name=value\n")
	for _, name := range missing {
		value := ""
		if v, ok := exported[name]; ok {
			// Exported variables live in [env] under their original name;
			// mirror the value so {{name}} resolves to the same thing.
			value = ConvertVarRefs(v.Value, ir, nil)
		}
		b.WriteString(fmt.Sprintf("%s = %q\n", name, value))
	}
	b.WriteString("\n")
	return b.String()
}

// writeSettings writes the [settings] section to the TOML output.
func writeSettings(b *strings.Builder, ir *MakefileIR) {
	b.WriteString("[settings]\n")
	if ir.DefaultGoal != "" {
		sanitized := SanitizeTargetName(ir.DefaultGoal)
		b.WriteString(fmt.Sprintf("default = %q\n", sanitized))
	}
	b.WriteString("\n")
}

// writeVariables writes the [variables] section with non-exported Make variables.
func writeVariables(b *strings.Builder, ir *MakefileIR) {
	vars := filterVars(ir.Variables, false)
	if len(vars) == 0 {
		return
	}

	b.WriteString("[variables]\n")
	for _, v := range vars {
		name := SanitizeVarName(v.Name)
		value, unsupported := convertVarRefs(v.Value, ir, nil)
		if len(unsupported) > 0 {
			// A make function bash cannot run would break every command that
			// interpolates this variable, so empty it and say so.
			writeFixme(b, unsupported, v.Name+" = "+v.Value)
			value = ""
		}
		b.WriteString(fmt.Sprintf("%s = %q\n", name, value))
	}
	b.WriteString("\n")
}

// writeEnv writes the [env] section with exported Make variables.
func writeEnv(b *strings.Builder, ir *MakefileIR) {
	vars := filterVars(ir.Variables, true)
	if len(vars) == 0 {
		return
	}

	b.WriteString("[env]\n")
	for _, v := range vars {
		value, unsupported := convertVarRefs(v.Value, ir, nil)
		if len(unsupported) > 0 {
			writeFixme(b, unsupported, v.Name+" = "+v.Value)
			value = ""
		}
		b.WriteString(fmt.Sprintf("%s = %q\n", v.Name, value))
	}
	b.WriteString("\n")
}

// writeCommands writes the [commands] section, converting Make targets to ImLazy commands.
func writeCommands(b *strings.Builder, ir *MakefileIR) {
	// Build set of target names for dependency resolution
	targetNames := eligibleTargetNames(ir)

	b.WriteString("[commands]\n\n")

	for _, t := range ir.Targets {
		if ShouldSkipTarget(t) {
			continue
		}
		writeCommand(b, ir, t, targetNames)
		b.WriteString("\n")
	}
}

// writeCommand writes the [commands.name] table for a single target.
// targetNames is the set of target names eligible to become dependencies.
func writeCommand(b *strings.Builder, ir *MakefileIR, t MakeTarget, targetNames map[string]bool) {
	// Recipe → run array. Converted before the table header so any
	// FIXME comments land above the command they belong to.
	var recipe strings.Builder
	if len(t.Recipe) > 0 {
		convertedRecipe := make([]string, 0, len(t.Recipe))
		for _, line := range t.Recipe {
			converted, unsupported := convertVarRefs(line, ir, &t)
			if len(unsupported) > 0 {
				writeFixme(b, unsupported, line)
				converted = unmigratedRecipeStub
			}
			convertedRecipe = append(convertedRecipe, cleanRecipeLine(converted))
		}
		recipe.WriteString(formatRunArray(convertedRecipe))
	}

	name := SanitizeTargetName(t.Name)
	if strings.Contains(name, ":") {
		// Namespaced names (npm-style "test:watch") need quoted keys.
		b.WriteString(fmt.Sprintf("[commands.%q]\n", name))
	} else {
		b.WriteString(fmt.Sprintf("[commands.%s]\n", name))
	}

	// Description from comment
	if t.Comment != "" {
		b.WriteString(fmt.Sprintf("desc = %q\n", t.Comment))
	}

	b.WriteString(recipe.String())

	// Dependencies — only include prerequisites that are also targets
	deps := filterDeps(t.Prerequisites, targetNames)
	if len(deps) > 0 {
		sanitizedDeps := make([]string, len(deps))
		for i, d := range deps {
			sanitizedDeps[i] = SanitizeTargetName(d)
		}
		b.WriteString(formatStringArray("dep", sanitizedDeps))
	}
}

// eligibleTargetNames returns the set of target names that become commands,
// i.e. those usable as dependencies.
func eligibleTargetNames(ir *MakefileIR) map[string]bool {
	names := make(map[string]bool)
	for _, t := range ir.Targets {
		if !ShouldSkipTarget(t) {
			names[t.Name] = true
		}
	}
	return names
}

// writeWarnings appends migration warnings and notes as TOML comments at the
// end of the output.
func writeWarnings(b *strings.Builder, ir *MakefileIR) {
	if len(ir.Notes) > 0 {
		b.WriteString("# Migration notes:\n")
		for _, n := range ir.Notes {
			b.WriteString(fmt.Sprintf("# - %s\n", n))
		}
		if len(ir.Warnings) > 0 {
			b.WriteString("\n")
		}
	}
	if len(ir.Warnings) == 0 {
		return
	}
	b.WriteString("# Migration warnings:\n")
	for _, w := range ir.Warnings {
		b.WriteString(fmt.Sprintf("# - %s\n", w))
	}
}

// unmigratedRecipeStub replaces a recipe line the migrator could not convert.
// Failing loudly beats handing bash a make function it cannot parse, or
// silently dropping the line.
const unmigratedRecipeStub = "echo 'imlazy: this recipe line was not migrated — see the FIXME in lazy.toml' >&2; exit 1"

// writeFixme emits a comment block flagging make syntax that needs a human.
func writeFixme(b *strings.Builder, unsupported []string, original string) {
	b.WriteString("# FIXME (imlazy migrate): could not convert ")
	b.WriteString(strings.Join(unsupported, ", "))
	b.WriteString("\n#   original: ")
	b.WriteString(collapseWhitespace(original))
	b.WriteString("\n")
}

// filterVars returns variables matching the export flag.
func filterVars(vars []MakeVar, exported bool) []MakeVar {
	var result []MakeVar
	for _, v := range vars {
		if v.Export == exported {
			result = append(result, v)
		}
	}
	return result
}

// filterDeps returns only prerequisites that are actual target names.
func filterDeps(prereqs []string, targetNames map[string]bool) []string {
	var deps []string
	for _, p := range prereqs {
		if targetNames[p] {
			deps = append(deps, p)
		}
	}
	return deps
}

// cleanRecipeLine removes leftover Make-isms from a converted recipe line.
// Strips {{q}} (Make's $(Q) quiet variable) and trims whitespace.
func cleanRecipeLine(line string) string {
	// $(Q) was already stripped in the parser, but if it appeared as a
	// variable reference it became {{q}} — strip that too
	line = strings.TrimPrefix(line, "{{q}}")
	line = strings.TrimSpace(line)
	return line
}

// formatRunArray formats a slice of strings as a TOML run array.
func formatRunArray(lines []string) string {
	if len(lines) == 1 {
		return fmt.Sprintf("run = [%q]\n", lines[0])
	}
	var b strings.Builder
	b.WriteString("run = [\n")
	for _, line := range lines {
		b.WriteString(fmt.Sprintf("  %q,\n", line))
	}
	b.WriteString("]\n")
	return b.String()
}

// formatStringArray formats a named TOML string array.
func formatStringArray(key string, items []string) string {
	if len(items) == 1 {
		return fmt.Sprintf("%s = [%q]\n", key, items[0])
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s = [", key))
	for i, item := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", item))
	}
	b.WriteString("]\n")
	return b.String()
}
