package parser

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// syncFixture writes a Makefile and a lazy.toml into a temp dir and chdirs
// there, since sync discovers both by walking up from the working directory.
func syncFixture(t *testing.T, makefile, config string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "Makefile"), []byte(makefile), 0644); err != nil {
		t.Fatal(err)
	}
	if config != "" {
		if err := os.WriteFile(filepath.Join(dir, "lazy.toml"), []byte(config), 0644); err != nil {
			t.Fatal(err)
		}
	}
	t.Chdir(dir)
	return dir
}

const syncMakefile = `BIN_NAME = app
DESTDIR =

.PHONY: build test lint
build:
	cargo build --release

test:
	cargo test --workspace

lint:
	cargo clippy -- -D warnings
	shellcheck scripts/*.sh
`

// The config below is deliberately hand-edited: build's recipe differs from
// the Makefile's and it carries a comment. Sync must not touch either.
const syncConfig = `# Generated by imlazy migrate from Makefile

[settings]
default = "build"

[variables]
bin_name = "app"

[commands]

# hand-tuned: the Makefile still says --release
[commands.build]
run = ["cargo build --release --locked"]

[commands.test]
run = ["cargo test --workspace"]
`

func TestSyncAddsNewCommands(t *testing.T) {
	dir := syncFixture(t, syncMakefile, syncConfig)

	result, err := Sync(SyncOptions{})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Added) != 1 || result.Added[0] != "lint" {
		t.Fatalf("added: got %v, want [lint]", result.Added)
	}

	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)

	if !strings.Contains(got, "[commands.lint]") {
		t.Errorf("lint not added:\n%s", got)
	}
	if !strings.Contains(got, `"cargo clippy -- -D warnings"`) {
		t.Errorf("lint recipe not converted:\n%s", got)
	}
	// The hand-tuned recipe and its comment survive untouched.
	if !strings.Contains(got, `run = ["cargo build --release --locked"]`) {
		t.Errorf("hand-edited build recipe was overwritten:\n%s", got)
	}
	if !strings.Contains(got, "# hand-tuned: the Makefile still says --release") {
		t.Errorf("comment was lost:\n%s", got)
	}
	if strings.Count(got, "[commands.build]") != 1 {
		t.Errorf("build duplicated:\n%s", got)
	}

	// And the result still parses as a config with every command present.
	cfg, err := loadConfigFromPath(filepath.Join(dir, "lazy.toml"), make(map[string]bool))
	if err != nil {
		t.Fatalf("synced config does not parse: %v", err)
	}
	for _, name := range []string{"build", "test", "lint"} {
		if _, ok := cfg.Commands[name]; !ok {
			t.Errorf("command %q missing after sync", name)
		}
	}
}

func TestSyncIsIdempotent(t *testing.T) {
	dir := syncFixture(t, syncMakefile, syncConfig)

	if _, err := Sync(SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}

	result, err := Sync(SyncOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Added) != 0 {
		t.Errorf("second sync added %v, want nothing", result.Added)
	}

	second, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Errorf("second sync changed the file:\n%s", string(second))
	}
}

func TestSyncDryRunDoesNotWrite(t *testing.T) {
	dir := syncFixture(t, syncMakefile, syncConfig)

	result, err := Sync(SyncOptions{DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Added) != 1 || result.Added[0] != "lint" {
		t.Fatalf("added: got %v, want [lint]", result.Added)
	}
	if !strings.Contains(result.Preview, "[commands.lint]") {
		t.Errorf("preview missing the new command:\n%s", result.Preview)
	}

	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != syncConfig {
		t.Errorf("dry run wrote to the file:\n%s", string(data))
	}
}

// A new command is useless if the variables it interpolates are missing, so
// they come along — spliced into the existing table, since TOML forbids
// declaring [variables] twice.
func TestSyncAddsReferencedVariables(t *testing.T) {
	makefile := `BIN_NAME = app
PREFIX = /usr/local

.PHONY: build install
build:
	cargo build

install:
	install -Dm755 target/release/$(BIN_NAME) "$(PREFIX)/bin/$(BIN_NAME)"
`
	config := `[variables]
bin_name = "app"

[commands]

[commands.build]
run = ["cargo build"]
`
	dir := syncFixture(t, makefile, config)

	if _, err := Sync(SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)

	if strings.Count(got, "[variables]") != 1 {
		t.Errorf("[variables] declared more than once:\n%s", got)
	}
	if !strings.Contains(got, `prefix = "/usr/local"`) {
		t.Errorf("referenced variable not added:\n%s", got)
	}
	if strings.Count(got, "bin_name =") != 1 {
		t.Errorf("existing variable duplicated:\n%s", got)
	}

	cfg, err := loadConfigFromPath(filepath.Join(dir, "lazy.toml"), make(map[string]bool))
	if err != nil {
		t.Fatalf("synced config does not parse: %v", err)
	}
	if cfg.Variables["prefix"] != "/usr/local" {
		t.Errorf("prefix: got %q", cfg.Variables["prefix"])
	}
}

// A trailing comment block introduces what follows it or stands alone; either
// way the new command belongs above it, not below.
func TestSyncInsertsAboveTrailingComments(t *testing.T) {
	config := `[commands]

[commands.build]
run = ["cargo build --release"]

# Migration notes:
# - something worth remembering
`
	dir := syncFixture(t, syncMakefile, config)

	if _, err := Sync(SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)

	if strings.Index(got, "[commands.lint]") > strings.Index(got, "# Migration notes:") {
		t.Errorf("new command landed below the trailing comments:\n%s", got)
	}
	if !strings.Contains(got, "# Migration notes:") {
		t.Errorf("trailing comments lost:\n%s", got)
	}
	if _, err := loadConfigFromPath(filepath.Join(dir, "lazy.toml"), make(map[string]bool)); err != nil {
		t.Fatalf("synced config does not parse: %v", err)
	}
}

// A target reachable under an alias is already in the config under another
// name, so re-adding it would collide.
func TestSyncSkipsAliasedTargets(t *testing.T) {
	config := `[commands]

[commands.build]
run = ["cargo build --release"]

[commands.check]
run = ["cargo test --workspace"]
alias = ["test", "lint"]
`
	syncFixture(t, syncMakefile, config)

	result, err := Sync(SyncOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Added) != 0 {
		t.Errorf("added %v, want nothing (both targets are aliased)", result.Added)
	}
}

func TestSyncWithoutConfigFails(t *testing.T) {
	syncFixture(t, syncMakefile, "")

	if _, err := Sync(SyncOptions{}); err == nil {
		t.Fatal("expected an error when no lazy.toml exists")
	} else if !strings.Contains(err.Error(), "migrate") {
		t.Errorf("error should point at migrate, got: %v", err)
	}
}

// The marker comment is committed alongside the config, so it must not carry
// one machine's absolute path.
func TestSyncMarkerCommentUsesBareFilename(t *testing.T) {
	dir := syncFixture(t, syncMakefile, syncConfig)

	if _, err := Sync(SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)

	if !strings.Contains(got, "# Added by imlazy sync from Makefile") {
		t.Errorf("marker comment missing or malformed:\n%s", got)
	}
	if strings.Contains(got, dir) {
		t.Errorf("marker comment leaked an absolute path:\n%s", got)
	}
}

// Blank lines must not stack up on each sync.
func TestSyncDoesNotAccumulateBlankLines(t *testing.T) {
	makefile := syncMakefile + "\n.PHONY: fmt\nfmt:\n\tcargo fmt --all\n"
	dir := syncFixture(t, makefile, syncConfig)

	if _, err := Sync(SyncOptions{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "lazy.toml"))
	if err != nil {
		t.Fatal(err)
	}
	if got := string(data); strings.Contains(got, "\n\n\n") {
		t.Errorf("run of blank lines in synced config:\n%q", got)
	}
}
